title: "👋 Hi, I'm Vishwas Karale"
description: "ML Software Engineer and Graduate Student at NYU"
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
