title: "Vishwas Karale’s Portfolio"
description: "ML Software Engineer and Graduate Student at NYU"
theme: hacker # GitHub Pages supports themes like 'minimal', 'cayman', 'jekyll-theme-hacker', etc.
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
